version: '3.8'
services:
  app:
    build: .
    volumes:
      - .:/app
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - REDIS_HOST=redis
    depends_on:
      - mysql
      - redis
    command: php-fpm

  web:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - .:/app
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app

  worker:
    build: .
    command: php artisan queue:work
    depends_on:
      - app
      - redis

  cron:
    build: .
    command: php artisan schedule:work
    depends_on:
      - app

  mysql:
    image: mysql:8
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379" 